version: '3.1'
services:
  API:
    build: ./
    image: ontop.jar
    ports:
      - "8080:8080"
    depends_on:
      - PostgreSQL
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/ontop
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_TABLE=schema_history
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=password
      - SPRING_FLYWAY_LOCATIONS=classpath:/db/migration
      - SPRING_FLYWAY_URL=jdbc:postgresql://PostgreSQL:5432/ontop

  PostgreSQL:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ontop
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5